## FST section

Generate VCF without AF = 0 variants for GST. The VCF is the same as the one used for the population structure module.

```{r}
# read random_snippet.vcf.gz from pop_structure module
vcf <- read.vcfR(file = "../04-pop_structure/random_snippet.vcf.gz")

# calculate af
afs <- maf(vcf)
# get AF > 0 rows
nonzero <- afs[, 4] > 0

# subset vcf
vcf_nonzero <- vcf[nonzero, ]
# write new vcf
write.vcf(vcf_nonzero, file = "random_variable_sites.vcf.gz")
```


## PBS section

Generate pre-processed data for calculating PBS. The `.fst` files are on the [project OneDrive](https://livejohnshopkins.sharepoint.com/:f:/s/mccoy_lab/EjdWX_Itt5FDjOFNw4K_FZYB7WsNuAlCAyEyATwp3K3wFA?e=inOnzI).

```{r}
# FST for RPS-CHB comparison
rps_chb <- read_tsv("chr11.rps.chb.fst", 
                    col_names = c("chr", "pos", "rps.af", "chb.af", "fst.rps.chb"))
# FST for RPS-PNG comparison
rps_png <- read_tsv("chr11.rps.png.fst", 
                    col_names = c("chr", "pos", "rps.af", "png.af", "fst.rps.png"))
# FST for PNG-CHB comparison
png_chb <- read_tsv("chr11.png.chb.fst", 
                    col_names = c("chr", "pos", "png.af", "chb.af", "fst.png.chb"))

# merge fst results
fst_results <- merge(rps_chb,
                     rps_png[, c("chr", "pos", "png.af", "fst.rps.png")],
             by = c("chr", "pos")) %>%
  merge(.,
        png_chb[, c("chr", "pos", "fst.png.chb")],
        by = c("chr", "pos")) %>%
  # drop nas
  drop_na() %>%
  # drop variants that are fixed in at least one population
  filter(rps.af > 0 & rps.af < 1 &
         png.af > 0 & png.af < 1 &
         chb.af > 0 & chb.af < 1) %>%
  # reorder columns
  .[, c("chr", "pos", "rps.af", "chb.af", "png.af",
        "fst.rps.chb", "fst.rps.png", "fst.png.chb")]
# write table
write.table(fst_results, file = "fst_results.txt",
            sep = "\t", quote = FALSE, col.names = TRUE, row.names = FALSE)
```
