```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# Python 

## Python Fundamentals

### Types of Data

**Integers** Integers are whole numbers, without a decimal point. For example:

* 2
* -3 
* 0

**Floats** Floats are numbers with a decimal point. For example: 

* 1.2
* -3.0
* 26/3 (This one doesn't actually have a decimal point written in by me, but is a float because the expression evaluates to 8.666)

**Strings** Strings are character data enclosed by single ' or double " quotation marks. Any text enclosed by quotes will be treated as a string.

* "My Grandpa's deck has no pathetic cards"
* '85.3'

Note the second example – `85.3` is a float; `"85.3"` is a string.

**Booleans** A Boolean has two possible values: `True` and `False`. These can be expressed interchangeably as `1` or `0`, respectively.  

### Variables

A variable is assigned using the equals sign, with this general syntax:

`variable_name = value`. 

For example:

* `composer = "buxtehude"` 
* `year = 1637` 

The data name can be almost anything. Here are the rules to consider when naming a variable:

* A variable name must start with a letter or underscore
* A variable name can only consist of letters, numbers, or underscores
* Variables are case sensitive (i.e. Python would interpret my_number, MY_NUMBER, and My_Number as different variables)
* Python has a set of "reserved words" that cannot be used as variable names. These are words that already have a set meaning in Python, such as 'True', 'False', 'for', and 'if'. A full list can be found here: https://www.programiz.com/python-programming/keywords-identifier

## Processing Tabular Data

## Plotting

## Lists

## Loops