---
title: "GTEx PCA"
author: "Stephanie Yan"
---

Old code where Rajiv did a gene expression PCA with some GTEx samples and found that they cluster based on cause of death.

## GTEx metadata

```{r}
# sample ID and corresponding tissue type
sample_annotations <- read_tsv("https://storage.googleapis.com/gtex_analysis_v8/annotations/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt") %>%
  filter(SAMPID %in% colnames(gtex))

# individuals, ID, sex, age range, cause of death (hardy scale)
subject_phenotypes <- read_tsv("https://storage.googleapis.com/gtex_analysis_v8/annotations/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt")
```

## PCA

```{r}
# extract IDs for `Heart - Atrial Appendage` samples
heart_aa <- sample_annotations %>%
  filter(SMTSD == "Heart - Atrial Appendage") %>%
  .$SAMPID

# subset heart_aa samples from gtex matrix
gtex_heart_aa <- as.matrix(gtex[, heart_aa])

# run PCA and extract the PCs stored in $x
pca <- prcomp(t(gtex_heart_aa))$x %>%
  # convert to a tibble
  as_tibble() %>%
  # select only the first three PCs
  dplyr::select(PC1, PC2, PC3) %>%
  # add the sample IDs
  mutate(SAMPID = heart_aa) %>%
  # use the sample IDs to get the annotations 
  left_join(sample_annotations, by = "SAMPID") %>%
  # reformat the sample IDs to subject IDs
  separate(col = SAMPID, sep = "-", 
           into = c("s1", "s2", "s3", "s4", "s5")) %>%
  mutate(SUBJID = paste(s1, s2, sep = "-")) %>%
  # use the subject IDs to get phenotypes
  left_join(subject_phenotypes, by = "SUBJID")
```

Plot PCA, coloring by cause of death:

```{r}
# normal pca
ggplot(data = pca,
       aes(x = PC1, y = PC2, color = factor(DTHHRDY))) +
  geom_point()
```
